import { Theme } from '../models/theme.model';

export const THEMES: Theme[] = [
    {
        name: 'Blush',
        rootClass: 'theme-blush',
        backgroundClass: 'bg-blush-100',
        textClass: 'text-blush-text',
        buttonClass: 'bg-blush hover:bg-blush-dark',
        iconButtonClass: 'text-blush-text hover:text-blush-dark',
        focusRingClass: 'focus:ring-blush-dark',
        ringColor: '#f8b4d9',
        progressColor: '#f8b4d9',
        progressTrackClass: 'bg-blush-100',
        progressFillClass: 'bg-blush',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🌸', name: 'Cherry Blossom' },
            { emoji: '🧁', name: 'Cupcake' },
            { emoji: '🎀', name: 'Ribbon' },
            { emoji: '🌟', name: 'Star' },
            { emoji: '🐣', name: 'Hatchling Chick' },
            { emoji: '🧸', name: 'Teddy Bear' },
            { emoji: '🥚', name: 'Mystery Egg' },
            { emoji: '🎈', name: 'Balloon' },
            { emoji: '🍓', name: 'Strawberry' },
            { emoji: '☁️', name: 'Cloud' },
            { emoji: '🧃', name: 'Juice Box' },
            { emoji: '🍩', name: 'Donut' },
            { emoji: '🍒', name: 'Cherries' },
            { emoji: '💗', name: 'Heart Sparkle' }
        ],
        confettiColors: ['#ffd6e8', '#ffeaf4', '#f8b4d9', '#fcd3e1', '#fff0f6']
    },
    {
        name: 'Galaxy',
        rootClass: 'theme-galaxy',
        backgroundClass: 'bg-indigo-950',
        textClass: 'text-indigo-300',
        buttonClass: 'bg-indigo-600 hover:bg-indigo-500',
        iconButtonClass: 'text-indigo-300 hover:text-indigo-400',
        focusRingClass: 'focus:ring-indigo-400',
        ringColor: '#6366f1',
        progressColor: '#6366f1',
        progressTrackClass: 'bg-indigo-900',
        progressFillClass: 'bg-indigo-400',
        modalBackgroundClass: 'bg-gray-100',
        badgeSet: [
            { emoji: '🌌', name: 'Milky Way' },
            { emoji: '🪐', name: 'Saturn' },
            { emoji: '🌠', name: 'Shooting Star' },
            { emoji: '✨', name: 'Sparkle' },
            { emoji: '🚀', name: 'Rocket' },
            { emoji: '🌑', name: 'New Moon' },
            { emoji: '👽', name: 'Alien' },
            { emoji: '🛰️', name: 'Satellite' },
            { emoji: '🔭', name: 'Telescope' },
            { emoji: '🛸', name: 'UFO' },
            { emoji: '🌟', name: 'Star' },
            { emoji: '🌙', name: 'Moon' },
            { emoji: '💫', name: 'Dizzy Star' },
            { emoji: '🧬', name: 'DNA Spiral' }
        ],
        confettiColors: ['#6366f1', '#8b5cf6', '#c4b5fd', '#d8b4fe', '#f3e8ff']
    },
    {
        name: 'Minty Fresh',
        rootClass: 'theme-mint',
        backgroundClass: 'bg-mint-100',
        textClass: 'text-mint-text',
        buttonClass: 'bg-mint hover:bg-mint-dark',
        iconButtonClass: 'text-mint-text hover:text-mint-dark',
        focusRingClass: 'focus:ring-mint-dark',
        ringColor: '#b3f5dd',
        progressColor: '#b3f5dd',
        progressTrackClass: 'bg-mint-100',
        progressFillClass: 'bg-mint',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🍃', name: 'Leaf' },
            { emoji: '🍏', name: 'Green Apple' },
            { emoji: '🌿', name: 'Herb' },
            { emoji: '🍈', name: 'Melon' },
            { emoji: '🐢', name: 'Turtle' },
            { emoji: '🥒', name: 'Cucumber' },
            { emoji: '🌱', name: 'Sprout' },
            { emoji: '🥝', name: 'Kiwi' },
            { emoji: '🧃', name: 'Green Juice' },
            { emoji: '🍀', name: 'Four Leaf Clover' },
            { emoji: '🐸', name: 'Frog' },
            { emoji: '👽', name: 'Broccoli' },
            { emoji: '🌲', name: 'Pine Tree' },
            { emoji: '🦎', name: 'Lizard' }
        ],
        confettiColors: ['#b3f5dd', '#d1fae5', '#a7f3d0', '#99f6e4', '#6ee7b7']
    }
];
