import { Theme } from '../models/theme.model';

export const THEMES: Theme[] = [
    {
        name: 'Blush',
        rootClass: 'theme-blush',
        backgroundClass: 'bg-blush-100',
        textClass: 'text-blush-text',
        buttonClass: 'bg-blush hover:bg-blush-dark',
        iconButtonClass: 'text-blush-text hover:text-blush-dark',
        focusRingClass: 'focus:ring-blush-dark',
        ringColor: '#f8b4d9',
        progressColor: '#f8b4d9',
        progressTrackClass: 'bg-blush-100',
        progressFillClass: 'bg-blush',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🌸', name: 'Cherry Blossom' },
            { emoji: '🧁', name: 'Cupcake' },
            { emoji: '🎀', name: 'Ribbon' },
            { emoji: '🌟', name: 'Star' },
            { emoji: '🐣', name: 'Hatchling Chick' },
            { emoji: '🧸', name: 'Teddy Bear' },
            { emoji: '🥚', name: 'Mystery Egg' },
            { emoji: '🎈', name: 'Balloon' },
            { emoji: '🍓', name: 'Strawberry' },
            { emoji: '☁️', name: 'Cloud' },
            { emoji: '🧃', name: 'Juice Box' },
            { emoji: '🍩', name: 'Donut' },
            { emoji: '🍒', name: 'Cherries' },
            { emoji: '💗', name: 'Heart Sparkle' }
        ],
        confettiColors: ['#ffd6e8', '#ffeaf4', '#f8b4d9', '#fcd3e1', '#fff0f6'],
        selectBackgroundClass: 'bg-white',
    },
    {
        name: 'Minty Fresh',
        rootClass: 'theme-mint',
        backgroundClass: 'bg-mint-100',
        textClass: 'text-mint-text',
        buttonClass: 'bg-mint hover:bg-mint-dark',
        iconButtonClass: 'text-mint-text hover:text-mint-dark',
        focusRingClass: 'focus:ring-mint-dark',
        ringColor: '#b3f5dd',
        progressColor: '#b3f5dd',
        progressTrackClass: 'bg-mint-100',
        progressFillClass: 'bg-mint',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🍃', name: 'Leaf' },
            { emoji: '🍏', name: 'Green Apple' },
            { emoji: '🌿', name: 'Herb' },
            { emoji: '🍈', name: 'Melon' },
            { emoji: '🐢', name: 'Turtle' },
            { emoji: '🥒', name: 'Cucumber' },
            { emoji: '🌱', name: 'Sprout' },
            { emoji: '🥝', name: 'Kiwi' },
            { emoji: '🧃', name: 'Green Juice' },
            { emoji: '🍀', name: 'Four Leaf Clover' },
            { emoji: '🐸', name: 'Frog' },
            { emoji: '👽', name: 'Broccoli' },
            { emoji: '🌲', name: 'Pine Tree' },
            { emoji: '🦎', name: 'Lizard' }
        ],
        confettiColors: ['#b3f5dd', '#d1fae5', '#a7f3d0', '#99f6e4', '#6ee7b7'],
        selectBackgroundClass: 'bg-white',
    },
    {
        name: 'Sunbeam',
        rootClass: 'theme-sunbeam',
        backgroundClass: 'bg-yellow-100',
        textClass: 'text-yellow-800',
        buttonClass: 'bg-yellow-400 hover:bg-yellow-500',
        iconButtonClass: 'text-yellow-800 hover:text-yellow-900',
        focusRingClass: 'focus:ring-yellow-500',
        ringColor: '#facc15',
        progressColor: '#facc15',
        progressTrackClass: 'bg-yellow-200',
        progressFillClass: 'bg-yellow-400',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🌞', name: 'Sunshine' },
            { emoji: '🌻', name: 'Sunflower' },
            { emoji: '🍯', name: 'Honey Pot' },
            { emoji: '💛', name: 'Yellow Heart' },
            { emoji: '🐝', name: 'Bee' },
            { emoji: '🥞', name: 'Pancakes' },
            { emoji: '🧺', name: 'Picnic Basket' },
            { emoji: '🍊', name: 'Orange' },
            { emoji: '🍋', name: 'Lemon' },
            { emoji: '🐥', name: 'Chick' },
            { emoji: '🌼', name: 'Daisy' },
            { emoji: '🧈', name: 'Butter' },
            { emoji: '📒', name: 'Notebook' },
            { emoji: '🏵️', name: 'Rosette' }
        ],
        confettiColors: ['#fef3c7', '#fde68a', '#fcd34d', '#fbbf24', '#f59e0b'],
        selectBackgroundClass: 'bg-white',
    },
    {
        name: 'Deep Sea',
        rootClass: 'theme-deepsea',
        backgroundClass: 'bg-cyan-950',
        textClass: 'text-cyan-200',
        buttonClass: 'bg-cyan-600 hover:bg-cyan-500',
        iconButtonClass: 'text-cyan-200 hover:text-cyan-300',
        focusRingClass: 'focus:ring-cyan-400',
        ringColor: '#22d3ee',
        progressColor: '#22d3ee',
        progressTrackClass: 'bg-cyan-900',
        progressFillClass: 'bg-cyan-600',
        modalBackgroundClass: 'bg-white',
        badgeSet: [
            { emoji: '🌊', name: 'Wave' },
            { emoji: '🐬', name: 'Dolphin' },
            { emoji: '🧜‍♀️', name: 'Mermaid' },
            { emoji: '🦑', name: 'Squid' },
            { emoji: '🐙', name: 'Octopus' },
            { emoji: '🐚', name: 'Seashell' },
            { emoji: '🐳', name: 'Whale' },
            { emoji: '🦈', name: 'Shark' },
            { emoji: '🔱', name: 'Trident' },
            { emoji: '⚓', name: 'Anchor' },
            { emoji: '🧭', name: 'Compass' },
            { emoji: '🌌', name: 'Ocean Stars' },
            { emoji: '🐠', name: 'Tropical Fish' },
            { emoji: '🏄‍♀️', name: 'Surfer' }
        ],
        confettiColors: ['#0e7490', '#06b6d4', '#22d3ee', '#67e8f9', '#a5f3fc'],
        selectBackgroundClass: 'bg-gray-800'
    },
    {
        name: 'Midnight',
        rootClass: 'theme-midnight',
        backgroundClass: 'bg-gray-950',
        textClass: 'text-gray-100',
        buttonClass: 'bg-gray-700 hover:bg-gray-600',
        iconButtonClass: 'text-gray-300 hover:text-white',
        focusRingClass: 'focus:ring-gray-400',
        ringColor: '#71717a',
        progressColor: '#71717a',
        progressTrackClass: 'bg-gray-800',
        progressFillClass: 'bg-gray-600',
        modalBackgroundClass: 'bg-gray-900',
        badgeSet: [
            { emoji: '🕶️', name: 'Shades' },
            { emoji: '🖤', name: 'Black Heart' },
            { emoji: '🦇', name: 'Bat' },
            { emoji: '🌑', name: 'New Moon' },
            { emoji: '🎱', name: '8 Ball' },
            { emoji: '🧤', name: 'Glove' },
            { emoji: '🖋️', name: 'Quill' },
            { emoji: '🧵', name: 'Thread' },
            { emoji: '🕯️', name: 'Candle' },
            { emoji: '🌫️', name: 'Fog' },
            { emoji: '🎩', name: 'Top Hat' },
            { emoji: '🧛', name: 'Vampire' },
            { emoji: '🛸', name: 'Alien' },
            { emoji: '🖇️', name: 'Paperclip' }
        ],
        confettiColors: ['#1f2937', '#4b5563', '#6b7280', '#9ca3af', '#d1d5db'],
        selectBackgroundClass: 'bg-gray-800'
    },
    {
        name: 'Galaxy',
        rootClass: 'theme-galaxy',
        backgroundClass: 'bg-indigo-950',
        textClass: 'text-indigo-300',
        buttonClass: 'bg-indigo-600 hover:bg-indigo-500',
        iconButtonClass: 'text-indigo-300 hover:text-indigo-400',
        focusRingClass: 'focus:ring-indigo-400',
        ringColor: '#6366f1',
        progressColor: '#6366f1',
        progressTrackClass: 'bg-indigo-900',
        progressFillClass: 'bg-indigo-400',
        modalBackgroundClass: 'bg-gray-100',
        badgeSet: [
            { emoji: '🌌', name: 'Milky Way' },
            { emoji: '🪐', name: 'Saturn' },
            { emoji: '🌠', name: 'Shooting Star' },
            { emoji: '✨', name: 'Sparkle' },
            { emoji: '🚀', name: 'Rocket' },
            { emoji: '🌑', name: 'New Moon' },
            { emoji: '👽', name: 'Alien' },
            { emoji: '🛰️', name: 'Satellite' },
            { emoji: '🔭', name: 'Telescope' },
            { emoji: '🛸', name: 'UFO' },
            { emoji: '🌟', name: 'Star' },
            { emoji: '🌙', name: 'Moon' },
            { emoji: '💫', name: 'Dizzy Star' },
            { emoji: '🧬', name: 'DNA Spiral' }
        ],
        confettiColors: ['#6366f1', '#8b5cf6', '#c4b5fd', '#d8b4fe', '#f3e8ff'],
        selectBackgroundClass: 'bg-gray-800',
    }
];
